name: CMake CI

on: [push, pull_request]

jobs:
  ctest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create build folder
      run: mkdir build
    - name: Compile
      working-directory: build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: build
      run: ctest -V
